# Generated by Django 4.1.7 on 2023-03-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'Register'},
        ),
    ]
